package com.example.demo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MarketingCampaignActiveExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public MarketingCampaignActiveExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCampaignNoIsNull() {
            addCriterion("CAMPAIGN_NO is null");
            return (Criteria) this;
        }

        public Criteria andCampaignNoIsNotNull() {
            addCriterion("CAMPAIGN_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignNoEqualTo(String value) {
            addCriterion("CAMPAIGN_NO =", value, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoNotEqualTo(String value) {
            addCriterion("CAMPAIGN_NO <>", value, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoGreaterThan(String value) {
            addCriterion("CAMPAIGN_NO >", value, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoGreaterThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_NO >=", value, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoLessThan(String value) {
            addCriterion("CAMPAIGN_NO <", value, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoLessThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_NO <=", value, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoLike(String value) {
            addCriterion("CAMPAIGN_NO like", value, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoNotLike(String value) {
            addCriterion("CAMPAIGN_NO not like", value, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoIn(List<String> values) {
            addCriterion("CAMPAIGN_NO in", values, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoNotIn(List<String> values) {
            addCriterion("CAMPAIGN_NO not in", values, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_NO between", value1, value2, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignNoNotBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_NO not between", value1, value2, "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeIsNull() {
            addCriterion("CAMPAIGN_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeIsNotNull() {
            addCriterion("CAMPAIGN_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeEqualTo(String value) {
            addCriterion("CAMPAIGN_TYPE =", value, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeNotEqualTo(String value) {
            addCriterion("CAMPAIGN_TYPE <>", value, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeGreaterThan(String value) {
            addCriterion("CAMPAIGN_TYPE >", value, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_TYPE >=", value, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeLessThan(String value) {
            addCriterion("CAMPAIGN_TYPE <", value, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeLessThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_TYPE <=", value, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeLike(String value) {
            addCriterion("CAMPAIGN_TYPE like", value, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeNotLike(String value) {
            addCriterion("CAMPAIGN_TYPE not like", value, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeIn(List<String> values) {
            addCriterion("CAMPAIGN_TYPE in", values, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeNotIn(List<String> values) {
            addCriterion("CAMPAIGN_TYPE not in", values, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_TYPE between", value1, value2, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeNotBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_TYPE not between", value1, value2, "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignNameIsNull() {
            addCriterion("CAMPAIGN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCampaignNameIsNotNull() {
            addCriterion("CAMPAIGN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignNameEqualTo(String value) {
            addCriterion("CAMPAIGN_NAME =", value, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameNotEqualTo(String value) {
            addCriterion("CAMPAIGN_NAME <>", value, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameGreaterThan(String value) {
            addCriterion("CAMPAIGN_NAME >", value, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameGreaterThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_NAME >=", value, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameLessThan(String value) {
            addCriterion("CAMPAIGN_NAME <", value, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameLessThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_NAME <=", value, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameLike(String value) {
            addCriterion("CAMPAIGN_NAME like", value, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameNotLike(String value) {
            addCriterion("CAMPAIGN_NAME not like", value, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameIn(List<String> values) {
            addCriterion("CAMPAIGN_NAME in", values, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameNotIn(List<String> values) {
            addCriterion("CAMPAIGN_NAME not in", values, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_NAME between", value1, value2, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignNameNotBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_NAME not between", value1, value2, "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignDescIsNull() {
            addCriterion("CAMPAIGN_DESC is null");
            return (Criteria) this;
        }

        public Criteria andCampaignDescIsNotNull() {
            addCriterion("CAMPAIGN_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignDescEqualTo(String value) {
            addCriterion("CAMPAIGN_DESC =", value, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescNotEqualTo(String value) {
            addCriterion("CAMPAIGN_DESC <>", value, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescGreaterThan(String value) {
            addCriterion("CAMPAIGN_DESC >", value, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescGreaterThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_DESC >=", value, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescLessThan(String value) {
            addCriterion("CAMPAIGN_DESC <", value, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescLessThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_DESC <=", value, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescLike(String value) {
            addCriterion("CAMPAIGN_DESC like", value, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescNotLike(String value) {
            addCriterion("CAMPAIGN_DESC not like", value, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescIn(List<String> values) {
            addCriterion("CAMPAIGN_DESC in", values, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescNotIn(List<String> values) {
            addCriterion("CAMPAIGN_DESC not in", values, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_DESC between", value1, value2, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignDescNotBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_DESC not between", value1, value2, "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgIsNull() {
            addCriterion("CAMPAIGN_PUBLISH_ORG is null");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgIsNotNull() {
            addCriterion("CAMPAIGN_PUBLISH_ORG is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgEqualTo(Integer value) {
            addCriterion("CAMPAIGN_PUBLISH_ORG =", value, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgNotEqualTo(Integer value) {
            addCriterion("CAMPAIGN_PUBLISH_ORG <>", value, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgGreaterThan(Integer value) {
            addCriterion("CAMPAIGN_PUBLISH_ORG >", value, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgGreaterThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_PUBLISH_ORG >=", value, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgLessThan(Integer value) {
            addCriterion("CAMPAIGN_PUBLISH_ORG <", value, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgLessThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_PUBLISH_ORG <=", value, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgIn(List<Integer> values) {
            addCriterion("CAMPAIGN_PUBLISH_ORG in", values, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgNotIn(List<Integer> values) {
            addCriterion("CAMPAIGN_PUBLISH_ORG not in", values, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_PUBLISH_ORG between", value1, value2, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignPublishOrgNotBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_PUBLISH_ORG not between", value1, value2, "campaignPublishOrg");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateIsNull() {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateIsNotNull() {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateEqualTo(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE =", value, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateNotEqualTo(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE <>", value, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateGreaterThan(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE >", value, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE >=", value, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateLessThan(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE <", value, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateLessThanOrEqualTo(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE <=", value, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateIn(List<Date> values) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE in", values, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateNotIn(List<Date> values) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE not in", values, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateBetween(Date value1, Date value2) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE between", value1, value2, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableStartDateNotBetween(Date value1, Date value2) {
            addCriterion("CAMPAIGN_AVAILABLE_START_DATE not between", value1, value2, "campaignAvailableStartDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateIsNull() {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateIsNotNull() {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateEqualTo(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE =", value, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateNotEqualTo(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE <>", value, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateGreaterThan(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE >", value, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE >=", value, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateLessThan(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE <", value, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateLessThanOrEqualTo(Date value) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE <=", value, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateIn(List<Date> values) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE in", values, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateNotIn(List<Date> values) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE not in", values, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateBetween(Date value1, Date value2) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE between", value1, value2, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignAvailableEndDateNotBetween(Date value1, Date value2) {
            addCriterion("CAMPAIGN_AVAILABLE_END_DATE not between", value1, value2, "campaignAvailableEndDate");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeIsNull() {
            addCriterion("CAMPAIGN_USE_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeIsNotNull() {
            addCriterion("CAMPAIGN_USE_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeEqualTo(String value) {
            addCriterion("CAMPAIGN_USE_START_TIME =", value, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeNotEqualTo(String value) {
            addCriterion("CAMPAIGN_USE_START_TIME <>", value, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeGreaterThan(String value) {
            addCriterion("CAMPAIGN_USE_START_TIME >", value, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_USE_START_TIME >=", value, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeLessThan(String value) {
            addCriterion("CAMPAIGN_USE_START_TIME <", value, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeLessThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_USE_START_TIME <=", value, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeLike(String value) {
            addCriterion("CAMPAIGN_USE_START_TIME like", value, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeNotLike(String value) {
            addCriterion("CAMPAIGN_USE_START_TIME not like", value, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeIn(List<String> values) {
            addCriterion("CAMPAIGN_USE_START_TIME in", values, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeNotIn(List<String> values) {
            addCriterion("CAMPAIGN_USE_START_TIME not in", values, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_USE_START_TIME between", value1, value2, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeNotBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_USE_START_TIME not between", value1, value2, "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeIsNull() {
            addCriterion("CAMPAIGN_USE_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeIsNotNull() {
            addCriterion("CAMPAIGN_USE_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeEqualTo(String value) {
            addCriterion("CAMPAIGN_USE_END_TIME =", value, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeNotEqualTo(String value) {
            addCriterion("CAMPAIGN_USE_END_TIME <>", value, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeGreaterThan(String value) {
            addCriterion("CAMPAIGN_USE_END_TIME >", value, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_USE_END_TIME >=", value, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeLessThan(String value) {
            addCriterion("CAMPAIGN_USE_END_TIME <", value, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeLessThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_USE_END_TIME <=", value, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeLike(String value) {
            addCriterion("CAMPAIGN_USE_END_TIME like", value, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeNotLike(String value) {
            addCriterion("CAMPAIGN_USE_END_TIME not like", value, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeIn(List<String> values) {
            addCriterion("CAMPAIGN_USE_END_TIME in", values, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeNotIn(List<String> values) {
            addCriterion("CAMPAIGN_USE_END_TIME not in", values, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_USE_END_TIME between", value1, value2, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeNotBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_USE_END_TIME not between", value1, value2, "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeIsNull() {
            addCriterion("CAMPAIGN_TOOL_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeIsNotNull() {
            addCriterion("CAMPAIGN_TOOL_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeEqualTo(String value) {
            addCriterion("CAMPAIGN_TOOL_TYPE =", value, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeNotEqualTo(String value) {
            addCriterion("CAMPAIGN_TOOL_TYPE <>", value, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeGreaterThan(String value) {
            addCriterion("CAMPAIGN_TOOL_TYPE >", value, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_TOOL_TYPE >=", value, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeLessThan(String value) {
            addCriterion("CAMPAIGN_TOOL_TYPE <", value, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeLessThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_TOOL_TYPE <=", value, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeLike(String value) {
            addCriterion("CAMPAIGN_TOOL_TYPE like", value, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeNotLike(String value) {
            addCriterion("CAMPAIGN_TOOL_TYPE not like", value, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeIn(List<String> values) {
            addCriterion("CAMPAIGN_TOOL_TYPE in", values, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeNotIn(List<String> values) {
            addCriterion("CAMPAIGN_TOOL_TYPE not in", values, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_TOOL_TYPE between", value1, value2, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeNotBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_TOOL_TYPE not between", value1, value2, "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagIsNull() {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagIsNotNull() {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagEqualTo(String value) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG =", value, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagNotEqualTo(String value) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG <>", value, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagGreaterThan(String value) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG >", value, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagGreaterThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG >=", value, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagLessThan(String value) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG <", value, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagLessThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG <=", value, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagLike(String value) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG like", value, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagNotLike(String value) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG not like", value, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagIn(List<String> values) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG in", values, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagNotIn(List<String> values) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG not in", values, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG between", value1, value2, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagNotBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_DUPLICATE_FLAG not between", value1, value2, "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberIsNull() {
            addCriterion("CAMPAIGN_MAX_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberIsNotNull() {
            addCriterion("CAMPAIGN_MAX_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberEqualTo(Integer value) {
            addCriterion("CAMPAIGN_MAX_NUMBER =", value, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberNotEqualTo(Integer value) {
            addCriterion("CAMPAIGN_MAX_NUMBER <>", value, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberGreaterThan(Integer value) {
            addCriterion("CAMPAIGN_MAX_NUMBER >", value, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_MAX_NUMBER >=", value, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberLessThan(Integer value) {
            addCriterion("CAMPAIGN_MAX_NUMBER <", value, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberLessThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_MAX_NUMBER <=", value, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberIn(List<Integer> values) {
            addCriterion("CAMPAIGN_MAX_NUMBER in", values, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberNotIn(List<Integer> values) {
            addCriterion("CAMPAIGN_MAX_NUMBER not in", values, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_MAX_NUMBER between", value1, value2, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignMaxNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_MAX_NUMBER not between", value1, value2, "campaignMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberIsNull() {
            addCriterion("CAMPAIGN_DAILY_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberIsNotNull() {
            addCriterion("CAMPAIGN_DAILY_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberEqualTo(Integer value) {
            addCriterion("CAMPAIGN_DAILY_NUMBER =", value, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberNotEqualTo(Integer value) {
            addCriterion("CAMPAIGN_DAILY_NUMBER <>", value, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberGreaterThan(Integer value) {
            addCriterion("CAMPAIGN_DAILY_NUMBER >", value, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_DAILY_NUMBER >=", value, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberLessThan(Integer value) {
            addCriterion("CAMPAIGN_DAILY_NUMBER <", value, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberLessThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_DAILY_NUMBER <=", value, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberIn(List<Integer> values) {
            addCriterion("CAMPAIGN_DAILY_NUMBER in", values, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberNotIn(List<Integer> values) {
            addCriterion("CAMPAIGN_DAILY_NUMBER not in", values, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_DAILY_NUMBER between", value1, value2, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignDailyNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_DAILY_NUMBER not between", value1, value2, "campaignDailyNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberIsNull() {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberIsNotNull() {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberEqualTo(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER =", value, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberNotEqualTo(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER <>", value, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberGreaterThan(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER >", value, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER >=", value, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberLessThan(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER <", value, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberLessThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER <=", value, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberIn(List<Integer> values) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER in", values, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberNotIn(List<Integer> values) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER not in", values, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER between", value1, value2, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_ACCOUNT_NUMBER not between", value1, value2, "campaignAccountNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusIsNull() {
            addCriterion("CAMPAIGN_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusIsNotNull() {
            addCriterion("CAMPAIGN_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusEqualTo(String value) {
            addCriterion("CAMPAIGN_STATUS =", value, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusNotEqualTo(String value) {
            addCriterion("CAMPAIGN_STATUS <>", value, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusGreaterThan(String value) {
            addCriterion("CAMPAIGN_STATUS >", value, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusGreaterThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_STATUS >=", value, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusLessThan(String value) {
            addCriterion("CAMPAIGN_STATUS <", value, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusLessThanOrEqualTo(String value) {
            addCriterion("CAMPAIGN_STATUS <=", value, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusLike(String value) {
            addCriterion("CAMPAIGN_STATUS like", value, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusNotLike(String value) {
            addCriterion("CAMPAIGN_STATUS not like", value, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusIn(List<String> values) {
            addCriterion("CAMPAIGN_STATUS in", values, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusNotIn(List<String> values) {
            addCriterion("CAMPAIGN_STATUS not in", values, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_STATUS between", value1, value2, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusNotBetween(String value1, String value2) {
            addCriterion("CAMPAIGN_STATUS not between", value1, value2, "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberIsNull() {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberIsNotNull() {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberEqualTo(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER =", value, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberNotEqualTo(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER <>", value, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberGreaterThan(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER >", value, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER >=", value, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberLessThan(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER <", value, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberLessThanOrEqualTo(Integer value) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER <=", value, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberIn(List<Integer> values) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER in", values, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberNotIn(List<Integer> values) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER not in", values, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER between", value1, value2, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andCampaignAccountMaxNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("CAMPAIGN_ACCOUNT_MAX_NUMBER not between", value1, value2, "campaignAccountMaxNumber");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedIsNull() {
            addCriterion("MEMBER_INVOLVED is null");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedIsNotNull() {
            addCriterion("MEMBER_INVOLVED is not null");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedEqualTo(String value) {
            addCriterion("MEMBER_INVOLVED =", value, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedNotEqualTo(String value) {
            addCriterion("MEMBER_INVOLVED <>", value, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedGreaterThan(String value) {
            addCriterion("MEMBER_INVOLVED >", value, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_INVOLVED >=", value, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedLessThan(String value) {
            addCriterion("MEMBER_INVOLVED <", value, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_INVOLVED <=", value, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedLike(String value) {
            addCriterion("MEMBER_INVOLVED like", value, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedNotLike(String value) {
            addCriterion("MEMBER_INVOLVED not like", value, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedIn(List<String> values) {
            addCriterion("MEMBER_INVOLVED in", values, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedNotIn(List<String> values) {
            addCriterion("MEMBER_INVOLVED not in", values, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedBetween(String value1, String value2) {
            addCriterion("MEMBER_INVOLVED between", value1, value2, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedNotBetween(String value1, String value2) {
            addCriterion("MEMBER_INVOLVED not between", value1, value2, "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(Integer value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(Integer value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(Integer value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(Integer value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(Integer value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<Integer> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<Integer> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(Integer value1, Integer value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(Integer value1, Integer value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andRsv1IsNull() {
            addCriterion("RSV1 is null");
            return (Criteria) this;
        }

        public Criteria andRsv1IsNotNull() {
            addCriterion("RSV1 is not null");
            return (Criteria) this;
        }

        public Criteria andRsv1EqualTo(String value) {
            addCriterion("RSV1 =", value, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1NotEqualTo(String value) {
            addCriterion("RSV1 <>", value, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1GreaterThan(String value) {
            addCriterion("RSV1 >", value, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1GreaterThanOrEqualTo(String value) {
            addCriterion("RSV1 >=", value, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1LessThan(String value) {
            addCriterion("RSV1 <", value, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1LessThanOrEqualTo(String value) {
            addCriterion("RSV1 <=", value, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1Like(String value) {
            addCriterion("RSV1 like", value, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1NotLike(String value) {
            addCriterion("RSV1 not like", value, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1In(List<String> values) {
            addCriterion("RSV1 in", values, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1NotIn(List<String> values) {
            addCriterion("RSV1 not in", values, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1Between(String value1, String value2) {
            addCriterion("RSV1 between", value1, value2, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv1NotBetween(String value1, String value2) {
            addCriterion("RSV1 not between", value1, value2, "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv2IsNull() {
            addCriterion("RSV2 is null");
            return (Criteria) this;
        }

        public Criteria andRsv2IsNotNull() {
            addCriterion("RSV2 is not null");
            return (Criteria) this;
        }

        public Criteria andRsv2EqualTo(String value) {
            addCriterion("RSV2 =", value, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2NotEqualTo(String value) {
            addCriterion("RSV2 <>", value, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2GreaterThan(String value) {
            addCriterion("RSV2 >", value, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2GreaterThanOrEqualTo(String value) {
            addCriterion("RSV2 >=", value, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2LessThan(String value) {
            addCriterion("RSV2 <", value, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2LessThanOrEqualTo(String value) {
            addCriterion("RSV2 <=", value, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2Like(String value) {
            addCriterion("RSV2 like", value, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2NotLike(String value) {
            addCriterion("RSV2 not like", value, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2In(List<String> values) {
            addCriterion("RSV2 in", values, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2NotIn(List<String> values) {
            addCriterion("RSV2 not in", values, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2Between(String value1, String value2) {
            addCriterion("RSV2 between", value1, value2, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv2NotBetween(String value1, String value2) {
            addCriterion("RSV2 not between", value1, value2, "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv3IsNull() {
            addCriterion("RSV3 is null");
            return (Criteria) this;
        }

        public Criteria andRsv3IsNotNull() {
            addCriterion("RSV3 is not null");
            return (Criteria) this;
        }

        public Criteria andRsv3EqualTo(String value) {
            addCriterion("RSV3 =", value, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3NotEqualTo(String value) {
            addCriterion("RSV3 <>", value, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3GreaterThan(String value) {
            addCriterion("RSV3 >", value, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3GreaterThanOrEqualTo(String value) {
            addCriterion("RSV3 >=", value, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3LessThan(String value) {
            addCriterion("RSV3 <", value, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3LessThanOrEqualTo(String value) {
            addCriterion("RSV3 <=", value, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3Like(String value) {
            addCriterion("RSV3 like", value, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3NotLike(String value) {
            addCriterion("RSV3 not like", value, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3In(List<String> values) {
            addCriterion("RSV3 in", values, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3NotIn(List<String> values) {
            addCriterion("RSV3 not in", values, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3Between(String value1, String value2) {
            addCriterion("RSV3 between", value1, value2, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv3NotBetween(String value1, String value2) {
            addCriterion("RSV3 not between", value1, value2, "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv4IsNull() {
            addCriterion("RSV4 is null");
            return (Criteria) this;
        }

        public Criteria andRsv4IsNotNull() {
            addCriterion("RSV4 is not null");
            return (Criteria) this;
        }

        public Criteria andRsv4EqualTo(String value) {
            addCriterion("RSV4 =", value, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4NotEqualTo(String value) {
            addCriterion("RSV4 <>", value, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4GreaterThan(String value) {
            addCriterion("RSV4 >", value, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4GreaterThanOrEqualTo(String value) {
            addCriterion("RSV4 >=", value, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4LessThan(String value) {
            addCriterion("RSV4 <", value, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4LessThanOrEqualTo(String value) {
            addCriterion("RSV4 <=", value, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4Like(String value) {
            addCriterion("RSV4 like", value, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4NotLike(String value) {
            addCriterion("RSV4 not like", value, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4In(List<String> values) {
            addCriterion("RSV4 in", values, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4NotIn(List<String> values) {
            addCriterion("RSV4 not in", values, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4Between(String value1, String value2) {
            addCriterion("RSV4 between", value1, value2, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv4NotBetween(String value1, String value2) {
            addCriterion("RSV4 not between", value1, value2, "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv5IsNull() {
            addCriterion("RSV5 is null");
            return (Criteria) this;
        }

        public Criteria andRsv5IsNotNull() {
            addCriterion("RSV5 is not null");
            return (Criteria) this;
        }

        public Criteria andRsv5EqualTo(String value) {
            addCriterion("RSV5 =", value, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5NotEqualTo(String value) {
            addCriterion("RSV5 <>", value, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5GreaterThan(String value) {
            addCriterion("RSV5 >", value, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5GreaterThanOrEqualTo(String value) {
            addCriterion("RSV5 >=", value, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5LessThan(String value) {
            addCriterion("RSV5 <", value, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5LessThanOrEqualTo(String value) {
            addCriterion("RSV5 <=", value, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5Like(String value) {
            addCriterion("RSV5 like", value, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5NotLike(String value) {
            addCriterion("RSV5 not like", value, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5In(List<String> values) {
            addCriterion("RSV5 in", values, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5NotIn(List<String> values) {
            addCriterion("RSV5 not in", values, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5Between(String value1, String value2) {
            addCriterion("RSV5 between", value1, value2, "rsv5");
            return (Criteria) this;
        }

        public Criteria andRsv5NotBetween(String value1, String value2) {
            addCriterion("RSV5 not between", value1, value2, "rsv5");
            return (Criteria) this;
        }

        public Criteria andCampaignNoLikeInsensitive(String value) {
            addCriterion("upper(CAMPAIGN_NO) like", value.toUpperCase(), "campaignNo");
            return (Criteria) this;
        }

        public Criteria andCampaignTypeLikeInsensitive(String value) {
            addCriterion("upper(CAMPAIGN_TYPE) like", value.toUpperCase(), "campaignType");
            return (Criteria) this;
        }

        public Criteria andCampaignNameLikeInsensitive(String value) {
            addCriterion("upper(CAMPAIGN_NAME) like", value.toUpperCase(), "campaignName");
            return (Criteria) this;
        }

        public Criteria andCampaignDescLikeInsensitive(String value) {
            addCriterion("upper(CAMPAIGN_DESC) like", value.toUpperCase(), "campaignDesc");
            return (Criteria) this;
        }

        public Criteria andCampaignUseStartTimeLikeInsensitive(String value) {
            addCriterion("upper(CAMPAIGN_USE_START_TIME) like", value.toUpperCase(), "campaignUseStartTime");
            return (Criteria) this;
        }

        public Criteria andCampaignUseEndTimeLikeInsensitive(String value) {
            addCriterion("upper(CAMPAIGN_USE_END_TIME) like", value.toUpperCase(), "campaignUseEndTime");
            return (Criteria) this;
        }

        public Criteria andCampaignToolTypeLikeInsensitive(String value) {
            addCriterion("upper(CAMPAIGN_TOOL_TYPE) like", value.toUpperCase(), "campaignToolType");
            return (Criteria) this;
        }

        public Criteria andCampaignDuplicateFlagLikeInsensitive(String value) {
            addCriterion("upper(CAMPAIGN_DUPLICATE_FLAG) like", value.toUpperCase(), "campaignDuplicateFlag");
            return (Criteria) this;
        }

        public Criteria andCampaignStatusLikeInsensitive(String value) {
            addCriterion("upper(CAMPAIGN_STATUS) like", value.toUpperCase(), "campaignStatus");
            return (Criteria) this;
        }

        public Criteria andMemberInvolvedLikeInsensitive(String value) {
            addCriterion("upper(MEMBER_INVOLVED) like", value.toUpperCase(), "memberInvolved");
            return (Criteria) this;
        }

        public Criteria andRsv1LikeInsensitive(String value) {
            addCriterion("upper(RSV1) like", value.toUpperCase(), "rsv1");
            return (Criteria) this;
        }

        public Criteria andRsv2LikeInsensitive(String value) {
            addCriterion("upper(RSV2) like", value.toUpperCase(), "rsv2");
            return (Criteria) this;
        }

        public Criteria andRsv3LikeInsensitive(String value) {
            addCriterion("upper(RSV3) like", value.toUpperCase(), "rsv3");
            return (Criteria) this;
        }

        public Criteria andRsv4LikeInsensitive(String value) {
            addCriterion("upper(RSV4) like", value.toUpperCase(), "rsv4");
            return (Criteria) this;
        }

        public Criteria andRsv5LikeInsensitive(String value) {
            addCriterion("upper(RSV5) like", value.toUpperCase(), "rsv5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}