server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ipp?allowMultiQueries=true&autoReconnect=true
    username: ipp
    password: ipp
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.example.demo