package com.example.demo.mapper;

import com.example.demo.model.MarketingCampaignActive;
import com.example.demo.model.MarketingCampaignActiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketingCampaignActiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    long countByExample(MarketingCampaignActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    int deleteByExample(MarketingCampaignActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String campaignNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    int insert(MarketingCampaignActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    int insertSelective(MarketingCampaignActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    List<MarketingCampaignActive> selectByExample(MarketingCampaignActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    MarketingCampaignActive selectByPrimaryKey(String campaignNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketingCampaignActive record, @Param("example") MarketingCampaignActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketingCampaignActive record, @Param("example") MarketingCampaignActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketingCampaignActive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_active
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketingCampaignActive record);
}