package com.example.demo.mapper;

import com.example.demo.model.MarketingCampaignDef;
import com.example.demo.model.MarketingCampaignDefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MarketingCampaignDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    long countByExample(MarketingCampaignDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    int deleteByExample(MarketingCampaignDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String campaignNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    int insert(MarketingCampaignDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    int insertSelective(MarketingCampaignDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    List<MarketingCampaignDef> selectByExample(MarketingCampaignDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    MarketingCampaignDef selectByPrimaryKey(String campaignNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MarketingCampaignDef record, @Param("example") MarketingCampaignDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MarketingCampaignDef record, @Param("example") MarketingCampaignDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MarketingCampaignDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table marketing_campaign_def
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MarketingCampaignDef record);
}